apiVersion: v1
kind: ConfigMap
metadata:
  name: heimdall-settings
  namespace: heimdall
data:
  slack-channel: "default-heimdall-channel"
  low-priority-cadence: "600s"
  medium-priority-cadence: "300s"
  high-priority-cadence: "60s"
  resource-fetch-cadence: "10s"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: heimdall-resources
  namespace: heimdall
