apiVersion: v1
kind: ConfigMap
metadata:
  name: heimdall-settings
  namespace: heimdall
data:
  slack-channel:
  low-priority-cadence:
  medium-priority-cadence:
  high-priority-cadence:
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: heimdall-resources
  namespace: heimdall
