apiVersion: v1
kind: Secret
metadata:
  name: heimdall-secret
  namespace: heimdall-controller
data:
  slack-token: eGFwcC0xLUEwNDlHMEtORE4yLTQzNDIwNDkzMjYyODktZDlhMDZhNDNlYmUzYjJiODVlNzRhMjc0ZmM0MDlmMzY1ZmE3NDkxYWE5YjcxN2M4OGJhYjNlMDdlZmM5NGQzYg==
type: Opaque
