name: Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Semantic version tag for the release'
        required: true
    
    
# Update the Latest tag
jobs:
  create-release-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{env.tag}}
          message: "Latest release"
          
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      -
        name: Build and push tag
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: kryanbeane/heimdall:${{env.tag}}
      -
        name: Build and push latest
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: kryanbeane/heimdall:latest
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Release
        uses: softprops/action-gh-release@v1

          
