name: Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Test
<<<<<<< HEAD
        run: go test -v ./...
=======
        run: go test -v ./...
>>>>>>> 45be949 (HEIMCTR-12: Added test and lint actions)
